language:
  - node_js

node_js:
  - 'lts/*'

env:
  - NODE_ENV=CI

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib

script:
  - npm run lint
