language:
  - node_js

node_js:
  - 'lts/*'

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm run lint
